[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Sy Tran", email = ""},
]
dependencies = [
    "temporalio>=1.5.1",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

